compiler: gcc
install:
  - wget "https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.2.1.tar.gz"
  - tar xvf mbedtls-2.2.1.tar.gz
  - pushd mbedtls-mbedtls-2.2.1 && cmake . && make && sudo make install && popd
script: cmake . && make
language: c
